<?php
/**
 * CreditCrewTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreditCrewTest Class Doc Comment
 *
 * @category    Class
 * @description CreditCrew
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreditCrewTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreditCrew"
     */
    public function testCreditCrew()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "original_language"
     */
    public function testPropertyOriginalLanguage()
    {
    }

    /**
     * Test attribute "episode_count"
     */
    public function testPropertyEpisodeCount()
    {
    }

    /**
     * Test attribute "overview"
     */
    public function testPropertyOverview()
    {
    }

    /**
     * Test attribute "origin_country"
     */
    public function testPropertyOriginCountry()
    {
    }

    /**
     * Test attribute "original_name"
     */
    public function testPropertyOriginalName()
    {
    }

    /**
     * Test attribute "vote_count"
     */
    public function testPropertyVoteCount()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "media_type"
     */
    public function testPropertyMediaType()
    {
    }

    /**
     * Test attribute "popularity"
     */
    public function testPropertyPopularity()
    {
    }

    /**
     * Test attribute "credit_id"
     */
    public function testPropertyCreditId()
    {
    }

    /**
     * Test attribute "backdrop_path"
     */
    public function testPropertyBackdropPath()
    {
    }

    /**
     * Test attribute "first_air_date"
     */
    public function testPropertyFirstAirDate()
    {
    }

    /**
     * Test attribute "vote_average"
     */
    public function testPropertyVoteAverage()
    {
    }

    /**
     * Test attribute "genre_ids"
     */
    public function testPropertyGenreIds()
    {
    }

    /**
     * Test attribute "poster_path"
     */
    public function testPropertyPosterPath()
    {
    }

    /**
     * Test attribute "original_title"
     */
    public function testPropertyOriginalTitle()
    {
    }

    /**
     * Test attribute "video"
     */
    public function testPropertyVideo()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "adult"
     */
    public function testPropertyAdult()
    {
    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {
    }

    /**
     * Test attribute "job"
     */
    public function testPropertyJob()
    {
    }

    /**
     * Test attribute "media_info"
     */
    public function testPropertyMediaInfo()
    {
    }
}
