<?php
/**
 * MovieDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MovieDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description MovieDetails
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MovieDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MovieDetails"
     */
    public function testMovieDetails()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "imdb_id"
     */
    public function testPropertyImdbId()
    {
    }

    /**
     * Test attribute "adult"
     */
    public function testPropertyAdult()
    {
    }

    /**
     * Test attribute "backdrop_path"
     */
    public function testPropertyBackdropPath()
    {
    }

    /**
     * Test attribute "poster_path"
     */
    public function testPropertyPosterPath()
    {
    }

    /**
     * Test attribute "budget"
     */
    public function testPropertyBudget()
    {
    }

    /**
     * Test attribute "genres"
     */
    public function testPropertyGenres()
    {
    }

    /**
     * Test attribute "homepage"
     */
    public function testPropertyHomepage()
    {
    }

    /**
     * Test attribute "related_videos"
     */
    public function testPropertyRelatedVideos()
    {
    }

    /**
     * Test attribute "original_language"
     */
    public function testPropertyOriginalLanguage()
    {
    }

    /**
     * Test attribute "original_title"
     */
    public function testPropertyOriginalTitle()
    {
    }

    /**
     * Test attribute "overview"
     */
    public function testPropertyOverview()
    {
    }

    /**
     * Test attribute "popularity"
     */
    public function testPropertyPopularity()
    {
    }

    /**
     * Test attribute "production_companies"
     */
    public function testPropertyProductionCompanies()
    {
    }

    /**
     * Test attribute "production_countries"
     */
    public function testPropertyProductionCountries()
    {
    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "releases"
     */
    public function testPropertyReleases()
    {
    }

    /**
     * Test attribute "revenue"
     */
    public function testPropertyRevenue()
    {
    }

    /**
     * Test attribute "runtime"
     */
    public function testPropertyRuntime()
    {
    }

    /**
     * Test attribute "spoken_languages"
     */
    public function testPropertySpokenLanguages()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "tagline"
     */
    public function testPropertyTagline()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "video"
     */
    public function testPropertyVideo()
    {
    }

    /**
     * Test attribute "vote_average"
     */
    public function testPropertyVoteAverage()
    {
    }

    /**
     * Test attribute "vote_count"
     */
    public function testPropertyVoteCount()
    {
    }

    /**
     * Test attribute "credits"
     */
    public function testPropertyCredits()
    {
    }

    /**
     * Test attribute "collection"
     */
    public function testPropertyCollection()
    {
    }

    /**
     * Test attribute "external_ids"
     */
    public function testPropertyExternalIds()
    {
    }

    /**
     * Test attribute "media_info"
     */
    public function testPropertyMediaInfo()
    {
    }

    /**
     * Test attribute "watch_providers"
     */
    public function testPropertyWatchProviders()
    {
    }
}
