<?php
/**
 * PersonDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PersonDetailTest Class Doc Comment
 *
 * @category    Class
 * @description PersonDetail
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PersonDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PersonDetail"
     */
    public function testPersonDetail()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "deathday"
     */
    public function testPropertyDeathday()
    {
    }

    /**
     * Test attribute "known_for_department"
     */
    public function testPropertyKnownForDepartment()
    {
    }

    /**
     * Test attribute "also_known_as"
     */
    public function testPropertyAlsoKnownAs()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "biography"
     */
    public function testPropertyBiography()
    {
    }

    /**
     * Test attribute "popularity"
     */
    public function testPropertyPopularity()
    {
    }

    /**
     * Test attribute "place_of_birth"
     */
    public function testPropertyPlaceOfBirth()
    {
    }

    /**
     * Test attribute "profile_path"
     */
    public function testPropertyProfilePath()
    {
    }

    /**
     * Test attribute "adult"
     */
    public function testPropertyAdult()
    {
    }

    /**
     * Test attribute "imdb_id"
     */
    public function testPropertyImdbId()
    {
    }

    /**
     * Test attribute "homepage"
     */
    public function testPropertyHomepage()
    {
    }
}
