<?php
/**
 * RadarrSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RadarrSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description RadarrSettings
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RadarrSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RadarrSettings"
     */
    public function testRadarrSettings()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "hostname"
     */
    public function testPropertyHostname()
    {
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
    }

    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {
    }

    /**
     * Test attribute "use_ssl"
     */
    public function testPropertyUseSsl()
    {
    }

    /**
     * Test attribute "base_url"
     */
    public function testPropertyBaseUrl()
    {
    }

    /**
     * Test attribute "active_profile_id"
     */
    public function testPropertyActiveProfileId()
    {
    }

    /**
     * Test attribute "active_profile_name"
     */
    public function testPropertyActiveProfileName()
    {
    }

    /**
     * Test attribute "active_directory"
     */
    public function testPropertyActiveDirectory()
    {
    }

    /**
     * Test attribute "is4k"
     */
    public function testPropertyIs4k()
    {
    }

    /**
     * Test attribute "minimum_availability"
     */
    public function testPropertyMinimumAvailability()
    {
    }

    /**
     * Test attribute "is_default"
     */
    public function testPropertyIsDefault()
    {
    }

    /**
     * Test attribute "external_url"
     */
    public function testPropertyExternalUrl()
    {
    }

    /**
     * Test attribute "sync_enabled"
     */
    public function testPropertySyncEnabled()
    {
    }

    /**
     * Test attribute "prevent_search"
     */
    public function testPropertyPreventSearch()
    {
    }
}
