<?php
/**
 * RequestBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RequestBodyTest Class Doc Comment
 *
 * @category    Class
 * @description RequestBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestBody"
     */
    public function testRequestBody()
    {
    }

    /**
     * Test attribute "media_type"
     */
    public function testPropertyMediaType()
    {
    }

    /**
     * Test attribute "media_id"
     */
    public function testPropertyMediaId()
    {
    }

    /**
     * Test attribute "tvdb_id"
     */
    public function testPropertyTvdbId()
    {
    }

    /**
     * Test attribute "seasons"
     */
    public function testPropertySeasons()
    {
    }

    /**
     * Test attribute "is4k"
     */
    public function testPropertyIs4k()
    {
    }

    /**
     * Test attribute "server_id"
     */
    public function testPropertyServerId()
    {
    }

    /**
     * Test attribute "profile_id"
     */
    public function testPropertyProfileId()
    {
    }

    /**
     * Test attribute "root_folder"
     */
    public function testPropertyRootFolder()
    {
    }

    /**
     * Test attribute "language_profile_id"
     */
    public function testPropertyLanguageProfileId()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }
}
