<?php
/**
 * SonarrSeriesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SonarrSeriesTest Class Doc Comment
 *
 * @category    Class
 * @description SonarrSeries
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SonarrSeriesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SonarrSeries"
     */
    public function testSonarrSeries()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "sort_title"
     */
    public function testPropertySortTitle()
    {
    }

    /**
     * Test attribute "season_count"
     */
    public function testPropertySeasonCount()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "overview"
     */
    public function testPropertyOverview()
    {
    }

    /**
     * Test attribute "network"
     */
    public function testPropertyNetwork()
    {
    }

    /**
     * Test attribute "air_time"
     */
    public function testPropertyAirTime()
    {
    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {
    }

    /**
     * Test attribute "remote_poster"
     */
    public function testPropertyRemotePoster()
    {
    }

    /**
     * Test attribute "seasons"
     */
    public function testPropertySeasons()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "profile_id"
     */
    public function testPropertyProfileId()
    {
    }

    /**
     * Test attribute "language_profile_id"
     */
    public function testPropertyLanguageProfileId()
    {
    }

    /**
     * Test attribute "season_folder"
     */
    public function testPropertySeasonFolder()
    {
    }

    /**
     * Test attribute "monitored"
     */
    public function testPropertyMonitored()
    {
    }

    /**
     * Test attribute "use_scene_numbering"
     */
    public function testPropertyUseSceneNumbering()
    {
    }

    /**
     * Test attribute "runtime"
     */
    public function testPropertyRuntime()
    {
    }

    /**
     * Test attribute "tvdb_id"
     */
    public function testPropertyTvdbId()
    {
    }

    /**
     * Test attribute "tv_rage_id"
     */
    public function testPropertyTvRageId()
    {
    }

    /**
     * Test attribute "tv_maze_id"
     */
    public function testPropertyTvMazeId()
    {
    }

    /**
     * Test attribute "first_aired"
     */
    public function testPropertyFirstAired()
    {
    }

    /**
     * Test attribute "last_info_sync"
     */
    public function testPropertyLastInfoSync()
    {
    }

    /**
     * Test attribute "series_type"
     */
    public function testPropertySeriesType()
    {
    }

    /**
     * Test attribute "clean_title"
     */
    public function testPropertyCleanTitle()
    {
    }

    /**
     * Test attribute "imdb_id"
     */
    public function testPropertyImdbId()
    {
    }

    /**
     * Test attribute "title_slug"
     */
    public function testPropertyTitleSlug()
    {
    }

    /**
     * Test attribute "certification"
     */
    public function testPropertyCertification()
    {
    }

    /**
     * Test attribute "genres"
     */
    public function testPropertyGenres()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "added"
     */
    public function testPropertyAdded()
    {
    }

    /**
     * Test attribute "ratings"
     */
    public function testPropertyRatings()
    {
    }

    /**
     * Test attribute "quality_profile_id"
     */
    public function testPropertyQualityProfileId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "root_folder_path"
     */
    public function testPropertyRootFolderPath()
    {
    }

    /**
     * Test attribute "add_options"
     */
    public function testPropertyAddOptions()
    {
    }
}
