<?php
/**
 * IssueApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * IssueApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IssueApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for issueCommentCommentIdDelete
     *
     * Delete issue comment.
     *
     */
    public function testIssueCommentCommentIdDelete()
    {
    }

    /**
     * Test case for issueCommentCommentIdGet
     *
     * Get issue comment.
     *
     */
    public function testIssueCommentCommentIdGet()
    {
    }

    /**
     * Test case for issueCommentCommentIdPut
     *
     * Update issue comment.
     *
     */
    public function testIssueCommentCommentIdPut()
    {
    }

    /**
     * Test case for issueGet
     *
     * Get all issues.
     *
     */
    public function testIssueGet()
    {
    }

    /**
     * Test case for issueIssueIdCommentPost
     *
     * Create a comment.
     *
     */
    public function testIssueIssueIdCommentPost()
    {
    }

    /**
     * Test case for issueIssueIdDelete
     *
     * Delete issue.
     *
     */
    public function testIssueIssueIdDelete()
    {
    }

    /**
     * Test case for issueIssueIdGet
     *
     * Get issue.
     *
     */
    public function testIssueIssueIdGet()
    {
    }

    /**
     * Test case for issueIssueIdStatusPost
     *
     * Update an issue's status.
     *
     */
    public function testIssueIssueIdStatusPost()
    {
    }

    /**
     * Test case for issuePost
     *
     * Create new issue.
     *
     */
    public function testIssuePost()
    {
    }
}
