<?php
/**
 * TmdbApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TmdbApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TmdbApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for backdropsGet
     *
     * Get backdrops of trending items.
     *
     */
    public function testBackdropsGet()
    {
    }

    /**
     * Test case for genresMovieGet
     *
     * Get list of official TMDb movie genres.
     *
     */
    public function testGenresMovieGet()
    {
    }

    /**
     * Test case for genresTvGet
     *
     * Get list of official TMDb movie genres.
     *
     */
    public function testGenresTvGet()
    {
    }

    /**
     * Test case for languagesGet
     *
     * Languages supported by TMDb.
     *
     */
    public function testLanguagesGet()
    {
    }

    /**
     * Test case for networkNetworkIdGet
     *
     * Get TV network details.
     *
     */
    public function testNetworkNetworkIdGet()
    {
    }

    /**
     * Test case for regionsGet
     *
     * Regions supported by TMDb.
     *
     */
    public function testRegionsGet()
    {
    }

    /**
     * Test case for studioStudioIdGet
     *
     * Get movie studio details.
     *
     */
    public function testStudioStudioIdGet()
    {
    }
}
